version: "1.1"
services:
  redis:
    image: "redis:alpine"
  oneframe:
    image: "paidyinc/one-frame"
  local-proxy:
    image: "bartosso/local-proxy"
    environment:
      TARGET_HOST: oneframe
      TARGET_PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - oneframe
      - redis
