version: "3"
services:
  redis:
    image: "redis:6.2.5"
    volumes:
      - ./redis:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis.conf
  oneframe:
    image: "paidyinc/one-frame"
  local-proxy:
    image: "bartosso/local-proxy"
    environment:
      TARGET_HOST: oneframe
      TARGET_PORT: 8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 8080:8080
    depends_on:
      - oneframe
      - redis
